### ISSUE TITLE
Problem Details (RFC7807)

### ISSUE THREAD

**Issue by franzliedke** [middlewares/json-exception-handler#2]
What about adding support for [RFC7807 "Problem Details"](https://tools.ietf.org/html/rfc7807), which is a spec for standardized error responses in JSON format?

Or is that an issue for the php-json-throwable repo? That seems to be used here, and it shows full exception details, which might be a little more than someone would expect (and want).

**Comment by shadowhand** [comment]
@franzliedke RFC 7807 is fantastic for known issues. This middleware is intended for exceptions that are unknown and leak past application try/catch blocks. HTTP Problem doesn't really work as a general purpose exception handler, IMO.

**Comment by franzliedke** [comment]
Okay, thanks for clarifying. Maybe that should be explained in the README - dumping out full traces is often not a good idea on production systems.
